spring:
  datasource:
    url: jdbc:mysql://localhost:3306/woniubookshop02?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  thymeleaf:
    cache: false
  redis:
    #     windows
    #     host: 127.0.0.1
    #     Linux
    host: 192.168.217.134
    port: 6379
    jedis:
      pool:
        max-active: 30
        max-idle: 10
        min-idle: 3
        max-wait: 3000
  mail:
    host: smtp.qq.com
    username: woniumrwang@qq.com  #用你自己的
    password: tbpdfwnywzlohgha   # 用你自己的  邮箱授权码
    default-encoding: utf-8
    port: 465
    properties:
      mail:
        debug: true
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.woniuxy
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

