spring:
  redis:
#     windows
#     host: 127.0.0.1
#     Linux
    host: 192.168.217.134
    port: 6379
    jedis:
      pool:
        max-active: 30
        max-idle: 10
        min-idle: 3
        max-wait: 3000